# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- einoSTAG

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.20.1'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: ls -R
  displayName: 'ls'

- task: DownloadSecureFile@1
  displayName: 'download backendend'
  inputs:
    secureFile: 'BACKEND_ENV_FILE' # string. Required. Secure File. 

- task: CopyFiles@2
  displayName: 'copy backendend'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: BACKEND_ENV_FILE
    TargetFolder: './backend'

- script: mv ./backend/BACKEND_ENV_FILE ./backend/.env
  displayName: 'rename'
- task: DownloadSecureFile@1
  displayName: 'download frontend'
  inputs:
    secureFile: 'FRONTEND_ENV_FILE' # string. Required. Secure File. 

- task: CopyFiles@2
  displayName: 'copy frontend'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: FRONTEND_ENV_FILE
    TargetFolder: './frontend'

- script: ls frontend -a
  displayName: 'ls'

- script: mv ./frontend/FRONTEND_ENV_FILE ./frontend/.env
  displayName: 'rename'

- script: ls -a ./frontend
  displayName: 'ls'

- script: file ./frontend/.env
  displayName: 'cat'



- script: |
    npm run build
  displayName: 'npm build'

- script: ls -R
  displayName: 'ls'

- task: CopyFilesOverSSH@0
  inputs:
      sshEndpoint: 'newadmin_junctionappeurope'
      sourceFolder: './backend/build'
      contents: '**' 
      targetFolder: './usr/share/nginx/html/build'
    # Advanced
      #isWindowsOnTarget: false # boolean. Target machine running Windows. Default: false.
      cleanTargetFolder: true 
      #cleanHiddenFilesInTarget: false # boolean. Optional. Use when cleanTargetFolder = true. Remove hidden files in target folder. Default: false.
      #readyTimeout: '20000' 
      overwrite: true 
      #failOnEmptySource: false # boolean. Fail if no files found to copy. Default: false.
      #flattenFolders: false # boolean. Flatten folders. Default: false.

- task: SSH@0
  inputs:
    sshEndpoint: 'newadmin_junctionappeurope'
    runOptions: 'commands' 
    commands: sudo systemctl reload nginx
    interactiveSession: true